#! /bin/bash

alias out="cd .."
alias back="cd -"
alias i2="open"

alias 22="v $DOTS/bash/brew/nav"
alias 2.="cd $DOTS"
alias 2c="cd $HOME/.config"
alias 2d="cd $HOME/Downloads"
alias 2l="cd $HOME/.local"
alias 2lb="cd $HOME/.local/bin"
alias 2ls="cd $HOME/.local/src"
alias 2v.="cd $DOTS/nvim"
alias 2v="cd $HOME/.config/nvim"
alias 2z="cd $DOTS/bash"

# generic navigation
function 2() {
  TARGET=$(fd \
    -t d \
    -d 3 \
    | sed 's/^..//' \
    | fzf \
    --height=10 +m \
    --no-mouse \
    --reverse \
    --no-info \
    --prompt="  " \
    --color='pointer:2')
  cd $TARGET
}
