#! /bin/bash

# vim
alias vim=$NVIM
alias v=$NVIM

# general
alias ct="printf '\033[2J\033[3J\033[1;1H'" # clear terminal
alias gup="pass git push"
alias ka="killall"
alias mon="while; do; clear; lt; sleep 1; done" # monitor directory
alias oc="octave"
alias py="python3"
alias zr="exec $SHELL -l" # reloads shell

# fuzzy finder
alias ff='fzf -m -1 -0 --no-bold'
alias fm='cd ${$(fd --type d --hidden --exclude .git | ff):-$(pwd)}'
alias ft='fm; tn'
alias fv='v $(ff)'
