#! /bin/zsh

alias out="cd .."
alias back="cd -"
alias i2="open"

# checkpoint declarations
export ARCHIVE="$REPOS/archive"
export PROJECTS="$REPOS/projects"
export ONE_KCJK="$HOME/OneDrive"
export ONE_NUS="$HOME/'OneDrive - National University of Singapore'"

# doc_start
alias 2.="v $REPOS/zsh/brew/nav"
alias 2a="cd $ARCHIVE"
alias 2c="cd $HOME/.config"
alias 2cf="cd $REPOS/codeforces"
alias 2d="cd $HOME/Downloads"
alias 2f="cd $HOME/files"
alias 2g="cd $ONE_KCJK/KCJK/'Good Shit'" 
alias 2h="cd $PROJECTS/hcanoe-telegram"
alias 2hs="cd $HOME/server"
alias 2l="cd $HOME/.local"
alias 2lb="cd $HOME/.local/bin"
alias 2ls="cd $HOME/.local/src"
alias 2lsf="cd $HOME/.local/share/fonts"
alias 2m="cd $REPOS/misc"
alias 2nus="ssh kevincjk@stu.comp.nus.edu.sg"
alias 2o="cd $ONE_KCJK/KCJK"
alias 2on="cd $ONE_NUS"
alias 2p="cd $PROJECTS"
alias 2pe="ssh -t kevincjk@stu.comp.nus.edu.sg ssh kevincjk@pe113.comp.nus.edu.sg"
alias 2r="cd $REPOS"
alias 2v.="cd $ZSH_DOTS/nvim"
alias 2v="cd $HOME/.config/nvim"
alias 2z="cd $ZSH_DOTS"
# doc_end

function 2,() {
  START="# doc_start"
  END="# doc_end"
  [ `uname` = "Linux" ] && cat $ZSH_DOTS/brew/nav \
    | sed -n "/^# doc_start/,/^$START/{p;/^$END/q}" \
    | sed "s/alias //g"
  [ `uname` = "Darwin" ] && cat $ZSH_DOTS/brew/nav \
    | sed -n "/^# doc_start/,/^$START/p;/^$END/q" \
    | sed "s/alias //g"
  unset START END
  return true
}

# goes to root of git repo
# function 2r() {
#   cd $(git rev-parse --show-toplevel)
# }

# to university folder
function 2mod() {
  cd /Users/kevin/'OneDrive - National University of Singapore'/Modules
  BASEDIR="."

  MODS=$(fd \
    -t d \
    -d 1 \
    --base-directory $BASEDIR \
    --exec basename)

  RES+="home\n$MODS"

  TARGET=$(echo $RES | fzf \
    --height=10 +m \
    --no-mouse \
    --reverse \
    --no-info \
    --prompt="  " \
    --color='pointer:2')

  case $TARGET in 
    "")
      unset RES TARGET MODS
      return true;;
    "home") cd $BASEDIR;;
    *) cd $BASEDIR/$TARGET;;
  esac

  unset RES TARGET MODS
}

# generic navigation
# g for jump
function 2() {
  TARGET=$(fd \
    -t d \
    -d 3 \
    | sed 's/^..//' \
    | fzf \
    --height=10 +m \
    --no-mouse \
    --reverse \
    --no-info \
    --prompt="  " \
    --color='pointer:2')
  cd $TARGET
}
