#! /bin/zsh

# for zshrc
rm -f ~/.zshrc
source ./scripts/zshlink

# for tmux.confg
rm -f ~/.tmux.conf
source ./scripts/tmuxlink

# for nvim configs
rm -rf $XDG_CONFIG_HOME/nvim
source ./scripts/nvimlink

# for kitty configs
rm -rf $XDG_CONFIG_HOME/kitty
source ./scripts/kittylink
