#! /bin/zsh

# for zshrc
rm -f ~/.zshrc
source ./links/zshlink

# for tmux.confg
rm -f ~/.tmux.conf
source ./links/tmuxlink

# for nvim configs
rm -rf $XDG_CONFIG_HOME/nvim
source ./links/nvimlink

# for kitty configs
rm -rf $XDG_CONFIG_HOME/kitty
source ./links/kittylink
