#! /bin/bash

# basic exports
export DOTS="~/ripples/fullstops"

# necessary installs
sudo apt install -y exa fzf fd-find neovim

# for bashrc
source ./scripts/bashlink

# for nvim configs
source ./scripts/nvimlink
