#! /bin/zsh

function ed() {
  case $1 in
  '.') vim $ZSH_DOTS/brew/edits;;
  'g'|'git') vim $HOME/.gitconfig;;
  'v'|'vim') vim $DOTS/vim/vimrc;;
  'z'|'zsh') vim $ZSH_DOTS/bashrc;;
  *) echo "nothing happened.";;
  esac
}
