#! /bin/zsh

# managing changes
alias gs="git-nu status" # git status
alias ga="git-nu add"
alias gaa="git-nu add --all"
alias grs="git-nu restore"
alias gd="git-nu diff"
alias gds="git-nu diff --staged"
alias gr="git-nu reset"
alias gp="git push"
alias gpu="git push -u origin HEAD"
alias gpl="git pull"
alias gplu="git pull upstream master"
alias gplo="git pull origin master"
alias gap="git-nu add -p"
alias gms="git merge --squash" # squash diff into one commit

# git commit
alias gc="git commit"
alias gcan="git commit --amend --no-edit"
function gcm() {
  if [ "$1" ]; then
    git commit -m $1
  else
    git commit
  fi
}

# git commit --amend
function gca() {
  if [ "$1" ]; then
    git commit --amend -m $1
  else
    git commit --amend
  fi
}

# managing branches
alias gco="git-nu checkout"
alias gcob="git-nu checkout -b"
alias gb="git-nu branch"
alias gbd="git-nu branch -d"

# git log
function gl() {
  [ "$1" ] && len=$1 || len=20
  git log --oneline --graph -n $len
}

# the laziest git function ever
function gq() {
  git-nu add .
  git commit -m ${1-"update"}
  git push
}

# misc
alias giti="v .gitignore"
alias gitm="v .gitmodules"
