#! /bin/zsh

alias out="cd .."
alias back="cd -"
alias i2="open"

# doc_start
alias 22="v $BASH_DOTS/brew/nav"
alias 2.="cd $DOTS"
alias 2c="cd $HOME/.config"
alias 2d="cd $HOME/Downloads"
alias 2l="cd $HOME/.local"
alias 2lb="cd $HOME/.local/bin"
alias 2ls="cd $HOME/.local/src"
alias 2v.="cd $DOTS/vim"
alias 2v="cd $HOME/.config/vim"
alias 2z="cd $ZSH_DOTS"
# doc_end

function 2,() {
  START="# doc_start"
  END="# doc_end"
  [ `uname` = "Linux" ] && cat $BASH_DOTS/brew/nav \
    | sed -n "/^# doc_start/,/^$START/{p;/^$END/q}" \
    | sed "s/alias //g"
  [ `uname` = "Darwin" ] && cat $BASH_DOTS/brew/nav \
    | sed -n "/^# doc_start/,/^$START/p;/^$END/q" \
    | sed "s/alias //g"
  unset START END
  return true
}

# goes to root of git repo
function 2r() {
  cd $(git rev-parse --show-toplevel)
}

# generic navigation
function 2() {
  TARGET=$(fd \
    -t d \
    -d 3 \
    | sed 's/^..//' \
    | fzf \
    --height=10 +m \
    --no-mouse \
    --reverse \
    --no-info \
    --prompt="  " \
    --color='pointer:2')
  cd $TARGET
}
