#! /bin/zsh

alias bk="cd -"
alias i2="open"

function ou() {
  if [ "$1" ]; then
    i=0
    while [ $i -lt $1 ]; do
      cd ..
      i=$(($i + 1))
    done
  else
    cd ..
  fi
}

# autojump
[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh

# checkpoint declarations
export ARCHIVE="$REPOS/archive"
export PROJECTS="$REPOS/projects"
export ONE_KCJK="$HOME/OneDrive"
export ONE_NUS="$HOME/'OneDrive - National University of Singapore'"

# doc_start
alias 22="v $ZSH_DOTS/brew/nav"
alias 2.="cd $DOTS"
alias 2a="cd $ARCHIVE"
alias 2c="cd $HOME/.config"
alias 2cc="cd $REPOS/code-comps"
alias 2d="cd $HOME/Downloads"
alias 2l="cd $HOME/.local"
alias 2lb="cd $HOME/.local/bin"
alias 2ls="cd $HOME/.local/src"
alias 2m="cd $REPOS/misc"
alias 2n="cd $REPOS/nus"
alias 2nl="cd $REPOS/nutrilab"
alias 2o="cd $ONE_KCJK/KCJK"
alias 2on="cd $ONE_NUS"
alias 2p="cd $PROJECTS"
alias 2pe="ssh penode"
alias 2r="cd $REPOS"
alias 2soc="ssh soctf"
alias 2stu="ssh stu"
alias 2sun="ssh sun"
alias 2ub="ssh ubuntu"
alias 2xlog="ssh xlog"
alias 2ta="cd $REPOS/nus/work/cs2030s_ay2425s1"
alias 2v.="cd $DOTS/nvim"
alias 2v="cd $HOME/.config/nvim"
alias 2z="cd $ZSH_DOTS"
# doc_end

function 2,() {
  START="# doc_start"
  END="# doc_end"
  [ $(uname) = "Linux" ] && cat $ZSH_DOTS/brew/nav |
    sed -n "/^# doc_start/,/^$START/{p;/^$END/q}" |
    sed "s/alias //g"
  [ $(uname) = "Darwin" ] && cat $ZSH_DOTS/brew/nav |
    sed -n "/^# doc_start/,/^$START/p;/^$END/q" |
    sed "s/alias //g"
  unset START END
  return true
}

# to university folder
function 2mod() {
  cd $REPOS/nus/modules
  BASEDIR="."

  MODS=$(fd \
    -t d \
    -d 1 \
    --base-directory $BASEDIR \
    --exec basename)

  RES+="home\n$MODS"

  TARGET=$(echo $RES | fzf \
    --height=10 +m \
    --no-mouse \
    --reverse \
    --no-info \
    --prompt="  " \
    --color='pointer:2')

  case $TARGET in
  "")
    unset RES TARGET MODS
    return true
    ;;
  "home") cd $BASEDIR ;;
  *) cd $BASEDIR/$TARGET ;;
  esac

  unset RES TARGET MODS
}

# generic navigation
function 2() {
  TARGET=$(fd \
    -t d \
    -d 3 |
    sed 's/^..//' |
    fzf \
      --height=10 +m \
      --no-mouse \
      --reverse \
      --no-info \
      --prompt="  " \
      --color='pointer:2')
  cd $TARGET
}
