#! /bin/zsh

# vim
alias vim=$NVIM
alias v=$NVIM

# general
alias ct="printf '\033[2J\033[3J\033[1;1H'" # clear terminal
alias gup="pass git push"
alias ka="killall"
alias mon="while; do; clear; lt; sleep 1; done" # monitor directory
alias oc="octave"
alias py="python3"
alias yb="yarn build"
alias yd="yarn dev"
alias zr="exec $SHELL -l" # reloads shell

# gcc gdb stuff
alias gdb="gdb-apple"

# fuzzy finder
alias ff='fzf -m -1 -0 --no-bold'
alias fm='cd ${$(fd --type d --hidden --exclude .git | ff):-$(pwd)}'
alias ft='fm; tn'
alias fv='v $(ff)'

# tmux shortcuts
alias tm="tmux"
alias td="tmux detach"
alias tn="tmux new -s"
alias ts="tmux ls"
alias ta="tmux attach-session -t"
alias tk="tmux kill-session -t"

# java commands
alias j="java"
alias jc="javac"
alias jfm="java -jar /$HOME/.config/misc/java-formatter.jar --replace"

# NUS specific
alias snus="ssh-copy-id kevincjk@stu.comp.nus.edu.sg"
