#! /bin/bash

export DOTS="~/fullstops";

function setup() {
  sourceDirs=();
  sourceDirs+=(core brew)
  for d in $sourceDirs[@]; do
    fs=($find $DOTS/$d -type f)
    for f in $fs[@]; do source "$f"; done
  done
}

setup

# use emacs keybindings in shell
bindkey -e

clear -x
