#! /bin/zsh 

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=$VIM
export MANPAGER='nvim +Man!'
export VIM_CONFIG="$HOME/.config/nvim"
export MYVIMRC="$VIM_CONFIG/vimrc"
export VIMINIT=":source $MYVIMRC"

# for nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
