#! /bin/zsh

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# clang
export CC=/opt/homebrew/opt/llvm/bin/clang
export CXX="/opt/homebrew/opt/llvm/bin/clang++"

# nvim stuff
export XDG_CONFIG_HOME="$HOME/.config"
export NVIM="nvim"
export EDITOR=$NVIM
export MANPAGER='nvim +Man!'
export VIM_CONFIG="$XDG_CONFIG_HOME/nvim"

# go
export GOPATH="/Users/kevin/.go"
export GOBIN="/Users/kevin/.go/bin"

# hadoop
export JAVA_HOME="/Users/kevin/.jenv/versions/openjdk64-17.0.1"
export HADOOP_ROOT_LOGGER="WARN,console"

# for nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# tstock
export ALPHAVANTAGE_API_KEY="27HKIKZ2ZI4WC89B"
