#! /bin/zsh

# listing files
alias ls="exa -a --group-directories-first --ignore-glob='.DS_Store'"
alias ll="exa -al --group-directories-first --ignore-glob='.DS_Store'"

# file tree
function lt() {
  # lt [path...] [depth]

  # lt
	[ -z $1 ] && exa --tree --level=2 && return

  # lt [depth]
	[ "$1" ] && [ -z "${1//[0-9]}" ] && exa --tree --level=$1 && return

	if [ -d $1 ]; then
    # lt [path...]
		[ -z $2 ] && exa --tree --level=2 -- $1 && return

    # lt [path...] [depth]
		[ "$2" ] && [ -z "${2//[0-9]}" ] && exa --tree --level=$2 -- $1 && return
	fi
}
