#! /bin/zsh

# listing files
alias ls="eza --group-directories-first --ignore-glob='.DS_Store'"
alias la="eza -a --group-directories-first --ignore-glob='.DS_Store'"
alias ll="eza -al --group-directories-first --ignore-glob='.DS_Store'"

# file tree
function lt() {
	# usage: lt <depth> <directory>
	# <depth> is optional, defaults to 2.
	# <directory> is optional, defaults to $PWD.
	[ -d $1 ] && [ -z $2 ] \
		&& eza -a --tree --level=2 -- $1 \
		|| eza -a --tree --level=${1-2} -- ${2-.}
}
