#! /bin/zsh

# append
path+=$HOME/.local/bin
path+=/opt/local/bin
path+=$HOME/.yarn/bin

# maven
path+=/$HOME/.apache-maven-3.9.9/bin

# golang
export PATH=$PATH:$(go env GOBIN)

# jenv (java env manager)
export PATH="$PATH:$HOME/.jenv/bin"
eval "$(jenv init -)"
