#! /bin/zsh

# append
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:/opt/local/bin"
export PATH="$PATH:$HOME/.yarn/bin"

# maven
export PATH="$PATH:$HOME/.apache-maven-3.9.9/bin"

# golang
export PATH=$PATH:$(go env GOBIN)

# jenv (java env manager)
export PATH="$PATH:$HOME/.jenv/bin"
eval "$(jenv init -)"
