#! /bin/zsh

# append
export PATH="$HOME/.local/bin:$PATH"
export PATH="/opt/local/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"

# maven
export PATH="$PATH:$HOME/.apache-maven-3.9.9/bin"

# golang
export PATH=$PATH:$(go env GOBIN)

# jenv (java env manager)
export PATH="$PATH:$HOME/.jenv/bin"
eval "$(jenv init -)"
