#! /bin/bash

function ed() {
  case $1 in
  '.') nvim $BASH_DOTS/brew/edits;;
  'g'|'git') nvim $HOME/.gitconfig;;
  'v'|'nvim') nvim $DOTS/nvim/lua/core/set.lua;;
  'b'|'bash') nvim $BASH_DOTS/bashrc;;
  *) echo "nothing happened.";;
  esac
}
