#! /bin/bash

# vim
alias vim=$NVIM
alias v=$NVIM

# general
alias ct="printf '\033[2J\033[3J\033[1;1H'" # clear terminal
alias gup="pass git push"
alias ka="killall"
alias mon="while; do; clear; lt; sleep 1; done" # monitor directory
alias py="python3"
alias yb="yarn build"
alias yd="yarn dev"
alias zr="exec $SHELL -l" # reloads shell

# fuzzy finder
alias ff='fzf -m -1 -0 --no-bold'
alias fm='cd ${$(fd --type d --hidden --exclude .git | ff):-$(pwd)}'
alias ft='fm; tn'
alias fv='v $(ff)'

# ssh
function scpxl() {
  scp -r $1 kevincjk@xlog:~
}

# simpler function for compiling cpp files
function gpp() {
  EXTENSION="cpp";

  if [ "$1" ]; then 
    g++ "$1.$EXTENSION" -o "$1.exe";
    chmod +x "$1.exe";
  else 
    echo "missing filename to compile";
  fi
}
