#! /bin/zsh 

# returns if shell is non-interactive
[ -z "$PS1" ] && return

# key variables
export REPOS="$HOME/ripples"
export DOTS="$REPOS/fullstops"
export ZSH_DOTS="$DOTS/zsh"

# zsh automagic completion
autoload -U compinit
compinit

function setup() {
  sourceDirs=()
  sourceDirs+=(core brew)
  for d in $sourceDirs[@]; do
    fs=($(find $ZSH_DOTS/$d -type f))
    for f in $fs[@]; do source "$f"; done
  done
}

setup

# use emacs keybindings in shell
bindkey -e

# printf '\033[2J\033[3J\033[1;1H' # clears screen
clear -x
py "$DOTS/quote/quotes.py"
birthdays date

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/kevin/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/kevin/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/kevin/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/kevin/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

