#! /bin/zsh

# returns if shell is non-interactive
[ -z "$PS1" ] && return

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# key variables
export REPOS="$HOME/ripples"
export DOTS="$REPOS/fullstops"
export ZSH_DOTS="$DOTS/zsh"

source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# use emacs keybindings in shell
bindkey -e

function setup() {
  sourceDirs=()
  sourceDirs+=(core brew)
  for d in $sourceDirs[@]; do
    fs=($(find $ZSH_DOTS/$d -type f))
    for f in $fs[@]; do source "$f"; done
  done
}

setup

# zsh automagic completion
autoload -U compinit
compinit

clear -x
py "$DOTS/quote/quotes.py"
birthdays date
