#! /bin/zsh 

# returns if shell is non-interactive
[ -z "$PS1" ] && return

# key variables
export REPOS="$HOME/ripples"
export DOTS="$REPOS/fullstops"
export ZSH_DOTS="$DOTS/zsh"

# zsh automagic completion
autoload -U compinit
compinit

function setup() {
  sourceDirs=()
  sourceDirs+=(core brew)
  for d in $sourceDirs[@]; do
    fs=($(find $ZSH_DOTS/$d -type f))
    for f in $fs[@]; do source "$f"; done
  done
}

setup

# use emacs keybindings in shell
bindkey -e

# printf '\033[2J\033[3J\033[1;1H' # clears screen
clear -x
py "$DOTS/quote/quotes.py"
birthdays date
