#! /bin/bash 

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# nvim stuff
export XDG_CONFIG_HOME="$HOME/.config"
export NVIM="nvim"
export EDITOR=$NVIM
export MANPAGER='nvim +Man!'
export VIM_CONFIG="$XDG_CONFIG_HOME/nvim"
