#! /bin/zsh

# append
path+=$HOME/.local/bin

# prepend
export PATH=$HOME/.yarn/bin:$PATH

# golang
export PATH=$PATH:$(go env GOBIN)

# jenv (java env manager)
export PATH="$PATH:$HOME/.jenv/bin"
eval "$(jenv init -)"
