#! /bin/bash


function branch() {
  b=$(git branch --show-current 2> /dev/null)
  [[ ! -z $b ]] && echo "\[\e[2;37m\][$b]\[\e[m\]"
}

# prompt config
oldps1="${debian_chroot:+($debian_chroot)}\u@\h:\w\$ ";

function prompt {
  local ARROW="--> ";
  local NODE="\[\e[1;35m\]\h:\[\e[m\]";
  local USER="\[\e[1;34m\]\w\[\e[m\]";
  local GREEN="\[\e[0;32m\]$ARROW\[\e[m\]";
  local RED="\[\e[0;31m\]$ARROW\[\e[m\]";
  
  export PS1=\`"if [ \$? == '0' ];
  then echo '$NODE$USER $(branch)\n$GREEN';
  else echo '$NODE$USER $(branch)\n$RED'; fi"\`;
}

export PROMPT_COMMAND=prompt
