#! /bin/bash 

# key variables
export DOTS="$HOME/ripples/fullstops"
export BASH_DOTS="$DOTS/bash"
export XDG_CONFIG_HOME="$HOME/.config"

sourceDirs=();
sourceDirs+=("core" "brew");
for d in ${sourceDirs[@]}; do
  fs=$(fdfind --type file --base-directory="$BASH_DOTS/$d");
  for f in ${fs[@]}; do
    source "$BASH_DOTS/$d/$f";
  done
done
